### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by graciazhang** [TonyBolger/LOGAN#1]
Hi, 

We are trying to install LOGAN in our environment but got the following error while compiling (the "make" step at LOGAN-Graph-Native).  Any idea what might got wrong? The gcc used was gcc4.8.2.

------------------------------------------------------------------------------------
Building file: src/mem/memPackStack.c
Invoking: GCC C Compiler
gcc -std=gnu99 -pedantic -pedantic-errors -Wall -Werror -Wshadow -Wdisabled-optimization -O3 -g -fno-tree-vectorize  -I"./src" -I"./cliSrc" -c -fmessage-length=0 -MMD -MP -MF"bin/cli/common/mem/memPackStack.d" -MT"bin/cli/common/mem/memPackStack.o" -o "bin/cli/common/mem/memPackStack.o" "src/mem/memPackStack.c"
src/mem/memPackStack.c: In function ‘packStackAllocWithSize’:
src/mem/memPackStack.c:81:31: error: array subscript is above array bounds [-Werror=array-bounds]
  int totalSize=PACKSTACK_SIZES[suggestedSizeIndex];
                               ^
cc1: all warnings being treated as errors

Thanks,
Yun Zhang
Research Scientist - Bioinformatics
Corteva Agriscience™, Agriculture Division of DowDuPont™

**Comment by graciazhang** [comment]
Thanks. I passed that step. Now I got this error: /usr/bin/ld: cannot find -lprofiler. Do you know which library is it? I googled this one and saw a post saying it is libgoogle-perftools-dev. Can you confirm? Thanks.

**Comment by TonyBolger** [comment]
Yes, it's the google profiler - part of [https://github.com/gperftools/gperftools](url).
If you have any problem, just remove it from the library list.

**Comment by graciazhang** [comment]
Thanks. I removed it from makefile and compiled successfully. Thanks.
